const handleLogin = async (e) => {
    e.preventDefault();
    try {
        const response = await authService.login({
            username: username,
            password: password
        });
        
        // Manejar el Ã©xito del login
        console.log('Login exitoso:', response);
        
    } catch (error) {
        // Manejar el error
        console.error('Error en login:', error);
    }
}; 